# Generated by Django 4.1.2 on 2022-10-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment',
            field=models.ImageField(default=None, upload_to='bukti_pembayaran'),
        ),
    ]
