# Generated by Django 4.1.2 on 2022-10-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_donation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.person'),
        ),
    ]
