# Generated by Django 4.1.2 on 2022-11-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donationhistory_delete_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationhistory',
            name='payment',
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='payment_receipt',
            field=models.ImageField(default=None, upload_to='payment_receipt'),
        ),
    ]
