# Generated by Django 4.1.2 on 2022-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_alter_donationhistory_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='payment_receipt',
            field=models.ImageField(default=None, upload_to='payment_receipt'),
        ),
    ]
