# Generated by Django 4.1.2 on 2022-12-12 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_alter_donationhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
