# Generated by Django 4.1.2 on 2022-12-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_alter_donationhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationhistory',
            name='payment_receipt',
            field=models.ImageField(null=True, upload_to='payment_receipt'),
        ),
    ]
