# Generated by Django 4.1.2 on 2022-11-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_transactionhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='amount',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='product_amount',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_amount',
            field=models.IntegerField(default=None),
        ),
    ]
