# Generated by Django 4.1.2 on 2022-12-12 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_transactionhistory_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 9, 58, 35, 124061, tzinfo=datetime.timezone.utc)),
        ),
    ]
