# Generated by Django 4.1.2 on 2022-11-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_rename_task_userstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstats',
            old_name='country',
            new_name='country_code',
        ),
    ]
