# Generated by Django 4.1.2 on 2022-12-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_remove_userstats_user_userstatssummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatssummary',
            name='most_donated_country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='userstatssummary',
            name='total_donated_tree',
            field=models.IntegerField(default=None),
        ),
    ]
