# Generated by Django 4.1.2 on 2022-12-11 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaderboard', '0005_userstatssummary_most_donated_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatssummary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
