# Generated by Django 4.1.2 on 2022-12-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_alter_userstatssummary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatssummary',
            name='most_donated_country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userstatssummary',
            name='total_donated_tree',
            field=models.IntegerField(default=0),
        ),
    ]
