# Generated by Django 4.1.2 on 2022-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_alter_userstatssummary_most_donated_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatssummary',
            name='synced',
            field=models.BooleanField(default=True),
        ),
    ]
