# Generated by Django 4.1.2 on 2022-10-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin_amount',
            field=models.IntegerField(default=0),
        ),
    ]
